### ISSUE TITLE
After latest update example no longer works

### ISSUE THREAD

**Issue by Kilill** [latonita/esphome-veml7700#1]
### Example in README.md needs updating

Previously working config now gives errors:

```
  Unknown value 'X1', valid options are '1/8X', '1/4X', '1X', '2X'.
  gain: X1
  integration_time: 100ms
  glass_attenuation_factor: 1.0
  ambient_light:
    name: Ambient light

  [white] is an invalid option for [sensor.veml7700]. Please check the indentation.
  white:
    name: White
```

the ```X1``` error is simple enough to fix. But what is the correct syntax for the other one?

**Comment by latonita** [comment]
@Kilill I do apologies, since its under development - things getting changed rapidly.
here is new config example:
```
sensor:
  - platform: veml7700
    address: 0x10
    update_interval: 30s
    auto_mode: true
    #gain: 1/8x
    #integration_time: 100ms
    # lux_compensation: false
    # glass_attenuation_factor: 1.10
    ambient_light:
      name: "Ambient light"
    # ambient_light_counts:
    #   name: "Ambient light counts"
    full_spectrum:
      name: "Full spectrum"
    # full_spectrum_counts:
    #   name: "Full spectrum counts"
    infrared: 
      name: "Near-IR"
    actual_integration_time:
      name: "Actual integration time"
    actual_gain:
      name: "Actual gain"

```
